---
baseurl: "https://blog.oro.nu/"
languageCode: en-us
title: "OroBlog"
theme: "terminal"
pygmentsCodefences: true
pygmentsCodefencesGuessSyntax: true
pygmentsStyle: "dracula"
pygmentsUseClasses: true

server:
  headers:
  - for: /*
    values:
      X-Frame-Options : "DENY"
      X-XSS-Protection : "1; mode=block"
      X-Content-Type-Options : "nosniff"
      Referrer-Policy : "strict-origin-when-cross-origin"
      Content-Security-Policy : "default-src 'self'; script-src 'self' 'unsafe-eval'
; style-src 'self' 'unsafe-inline'; font-src 'self';
  img-src 'self'; base-uri 'none'; form-action 'none'; connect-src ws://localhost:1313; frame-ancestors 'none'"

markup:
  highlight:
    noClasses: false
    style: "dracula"

params:
  themeColor: green
  showMenuItems: 2
  showLanguageSelector: false
  fullWidthTheme: false
  centerTheme: true

languages:
  en:
    languageName: English
    title: OroBlog
    menuMore: Show more
    readMore: Read more
    readOtherPosts: Read other posts

    params:
      logo:
        logoText: OroBlog
        logoHomeLink: /

    menu:
      main:
      - identifier: home
        name: Home
        url: /
        weight: 1
      - identifier: about
        name: About
        url: /about/
